name: Christian Larrea
favicon: null
layout_spectrum: 1
typography_spectrum: 0.7258065
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d6c1ae'
    - '#6a6e7a'
    - '#36251d'
    - '#a9543f'
    - '#ffffe0'
  brandStrength: 0
  lightness: 0.2580645
  saturation: 0.4963297
  rhythmicContrast: 0.7724015
purpose: []
