layout_spectrum: 1
color:
  saturation: 0.4963297
  lightness: 0.2580645
  brandStrength: 1
  brandColors:
    - '#FFFFFF'
    - '#C79275'
    - '#77413A'
    - '#2F8832'
    - '#65C65C'
  rhythmicContrast: 0.7724015
typography_spectrum: 0.7258065
name: Christian Larrea
