layout_spectrum: 0.3996719
typography_spectrum: 0.1724747
color:
  saturation: 0.4963297
  lightness: 0.1775794
  brandStrength: 0.6290323
  brandColors:
    - '#D0BCAB'
    - '#F9E8D1'
    - '#39281F'
    - '#6C6D79'
    - '#644C3A'
  rhythmicContrast: 0.4745849
name: Christian Larrea
